// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineExaminationSystem.Entities;

// 5. INHERIT
public partial class Student : Person
{
    // 6. COMMENT
    //public int Id { get; set; }

    public int? DeptId { get; set; }

    public string Ssn { get; set; }

    public virtual Department Dept { get; set; }

    //7. COMMENT

    //public virtual Person IdNavigation { get; set; }

    public virtual ICollection<StudentAnswerQuestion> StudentAnswerQuestions { get; set; } = new List<StudentAnswerQuestion>();

    public virtual ICollection<StudentExam> StudentExams { get; set; } = new List<StudentExam>();

    public virtual ICollection<Course> CIds { get; set; } = new List<Course>();
}